In [1]:
import numpy as np
import pandas as pd
import re  # for regular expression matching
from python_functions import data_loader

# Load the processed data
Hotel_Reviews = data_loader()

In [2]:
#Hotel_Reviews = pd.read_csv("../Scraping/slim_data_11_12_2024.csv")
Hotel_Reviews

,Hotel_Name,Review_Date,Positive_Review,Negative_Review,Reviewer_Score,Reviewer_Nationality,address,price,Translated_Positive_Review,Translated_Negative_Review,Country,date_object,month,num_date_object
0,11City Rooms,02-12-2023 00:00:00,On arrival we were warmly welcomed and made to...,Nothing,10.0,India,Chania Altstadt Chania,€ 311,The landlord was extremely accommodating. For ...,"The steep stairs up to the room, but the landl...",<NA>,2023-02-12,2,0.117808
1,11City Rooms,10-18-2024 00:00:00,The location was great right in the middle of ...,This isn't specific to the property but parkin...,10.0,United States,Chania Altstadt Chania,€ 311,Best host ever Thank you very very much! Great...,NaN,<NA>,2024-10-18,10,0.800000
2,11City Rooms,10-15-2024 00:00:00,The location was perfect. I loved the fair siz...,The Small Room with Balcony is exactly that. I...,10.0,United Kingdom,Chania Altstadt Chania,€ 311,No breakfast but the location allows access in...,NaN,<NA>,2024-10-15,10,0.791781
3,11City Rooms,10-07-2024 00:00:00,Second stay here perfect as always. Really rec...,Nothing the room was quite this time and reall...,10.0,France,Chania Altstadt Chania,€ 311,Very warm welcome. Quiet and comfortable night.,Accommodation in a pedestrian street. No car a...,<NA>,2024-10-07,10,0.769863
4,11City Rooms,10-07-2024 00:00:00,Everything was perfect !!! Giannis was so nice...,The room is a bit noisy during the night just ...,10.0,France,Chania Altstadt Chania,€ 311,Manoli and his wife Marie were exceptional hos...,Difficult to park a car.,<NA>,2024-10-07,10,0.769863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149230,Zorbas,08-30-2022 00:00:00,NaN,NaN,10.0,Austria,Soúgia,€ 283,NaN,NaN,<NA>,2022-08-30,8,0.663014
149231,Zorbas,08-10-2022 00:00:00,NaN,NaN,10.0,Austria,Soúgia,€ 283,NaN,NaN,<NA>,2022-08-10,8,0.608219
149232,Zorbas,08-05-2022 00:00:00,NaN,NaN,10.0,Greece,Soúgia,€ 283,NaN,NaN,<NA>,2022-08-05,8,0.594521
149233,Zorbas,07-24-2022 00:00:00,NaN,NaN,10.0,Czech Republic,Soúgia,€ 283,NaN,NaN,<NA>,2022-07-24,7,0.561644
149234,Zorbas,08-16-2023 00:00:00,NaN,NaN,7.0,Italy,Soúgia,€ 283,NaN,NaN,<NA>,2023-08-16,8,0.624658

In [6]:


# Calculate trip time and start date
trip_time = 356
trip_start = Hotel_Reviews["date_object"].max() - pd.Timedelta(days=trip_time)
booking_time = trip_start
attention_window = 356 

# Calculate time reference
Hotel_Reviews["time_ref"] = (Hotel_Reviews["date_object"] - booking_time).dt.days / 30.5

# Filter detection and test data
detection_data = Hotel_Reviews[(Hotel_Reviews["date_object"] < booking_time) &
                               (Hotel_Reviews["date_object"] > (booking_time - pd.Timedelta(days=attention_window)))]

test_data = Hotel_Reviews[(Hotel_Reviews["date_object"] > trip_start) &
                           (Hotel_Reviews["date_object"] < (trip_start + pd.Timedelta(days=trip_time)))]

attention_window_timedelta = pd.Timedelta(days=attention_window)

# Filter the data
my_data = Hotel_Reviews[Hotel_Reviews['date_object'] > (booking_time - attention_window_timedelta)]

# Add a 'group' column with 'before' and 'after' categories
my_data['group'] = pd.Categorical(
    ['before' if date < booking else 'after' for date, booking in zip(my_data['date_object'], booking_time)],
    categories=['before', 'after'],
    ordered=True
)

TypeError: 'Timestamp' object is not iterable